<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>捷库sns安装-Powered by gk.com</title>
    <?php 
    	echo $this->loadscript("/js/jquery-1.7.2.min.js");
    	echo $this->loadscript("/asset/install/css/style.css");
    ?>
</head>
<body>
<div id="install">
<?php echo $this->layout()->content; ?>
</div>
</body>
</html>
