<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->setseo($this->seo,"title");?>-Powered by gk.com</title>
    <meta name="Keywords" content="<?php echo $this->setseo($this->seo,"keywords");?>"/>
    <meta name="Description" content="<?php echo $this->setseo($this->seo,"descr");?>"/>
 <?php 
echo $this->loadscript("style/css/gui.css");
echo $this->loadscript("style/css/login-reg.css");
?>   
<link rel="shortcut icon" href="/res/favicon.ico" />
<?php 
echo $this->loadscript("js/jquery-1.7.2.min.js");
echo $this->loadscript("js/easydialog/easydialog.min.js");
echo $this->loadscript("js/easydialog/easydialog.css");
echo $this->loadscript("js/util.js");
?>
</head>
<body>
    <div class="container">
<?php echo $this->header();?>
  <?php echo $this->layout()->content; ?>
<?php echo $this->footer();?>
    </div>
    </body>
</html>