;<?php /*
[production]
site.config.siteName = "捷库 SNS 系统"
site.config.domain = "gk.com"
site.config.seo.home.title = "捷库(深圳)"
site.config.seo.home.keywords = "捷库|sns|开源|社区"
site.config.seo.home.descr = "捷库,开源社区"
site.config.coin.user.reg = "5"
site.config.coin.site.arc.add = "3"
site.config.coin.site.arc.delete = "5"
site.config.coin.group.arc.add = "3"
site.config.coin.group.arc.delete = "5"
site.config.coin.ask.arc.add = "3"
site.config.coin.ask.arc.delete = "5"
site.config.coin.ask.reply.add = "2"
site.config.coin.ask.reply.delete = "3"
site.config.coin.reply.add = "1"
site.config.coin.reply.delete = "3"
site.config.ask.helptag.id = "11"
site.config.group.my.id = "1"
site.config.guidelines.id = "5"
site.config.secret.id = "6"
site.config.reg.id = "4"
site.config.relief.id = "3"
site.config.linkman.id = "2"
site.config.aboutme.id = "1"
site.config.daren = "WindTalker"
site.smtp.SMTP.HOST = "smtp.exmail.qq.com"
site.smtp.SMTP.PORT = "25"
site.smtp.SMTP.SSL = "0"
site.smtp.SMTP.USERNAME = "admin@gk.com"
site.smtp.SMTP.PASSWORD = "xxxxx"
site.smtp.SMTP.AUTH = "1"
site.smtp.SMTP.CHARSET = "utf-8"
site.smtp.SMTP.FROMTO = "admin@gk.com"
site.smtp.SMTP.FROMNAME = "管理员"
site.smtp.SMTP.DEBUG = "0"
site.reg.sendemail = "0"
site.coin.needyanzheng = "30"
site.coin.name = "捷库币"
site.my.recommend = "1"
static_version = "20140322"
app.user.openlogin.qq.appkey = ""
app.user.openlogin.qq.appsecret = ""


;*/